name: Fracktory macOS Installer
run-name: 5.8.0 for macOS-${{ inputs.architecture }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      installer_name:
        description: 'Name of the .pkg'
        default: 'Fracktory_installer'
        required: false
        type: string

      app_name:
        description: 'Name of the Application in the installer'
        default: 'Fracktory'
        required: false
        type: string

      conan_args:
        description: '5.6 Conan args: eq.: --require-override'
        default: ''
        required: false
        type: string

      enterprise:
        description: 'Build Cura as an Enterprise edition'
        default: false
        required: true
        type: boolean

      staging:
        description: 'Use staging API'
        default: false
        required: true
        type: boolean

      architecture:
        description: 'Architecture'
        required: true
        default: 'x86_64'
        type: string

      operating_system:
        description: 'OS'
        required: true
        default: 'macOS-latest'
        type: string

      conan_internal:
        required: false
        default: false
        type: boolean

permissions:
  contents: read

env:
  # Set any necessary environment variables here

jobs:
  build:
    runs-on: ${{ inputs.operating_system }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          # Install required dependencies, e.g., Conan, etc.
          pip install conan

      - name: Build Application
        run: |
          # Add your build commands here
          # Example: conan install . ${{ inputs.conan_args }}
          # Example: build your application

      - name: Create Installer
        run: |
          # Create the installer package
          # Example: pkgbuild --root ./build --identifier com.example.fracktory --version 1.0 --install-location /Applications Fracktory_installer.pkg

      - name: Upload Installer
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.installer_name }}-${{ github.run_id }}.pkg
          path: Fracktory_installer.pkg
